name: BackEnd
on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    name: build da imagem e push para o docker hub
    runs-on: ubuntu-latest
    steps:
      - name: configurando QEMU
        uses: actions/checkout@v3

      - name: setando Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: logando no docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/nolex_front

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nolex_front:latest
